/* eslint-disable no-console */
import { loadMonorepoEnv } from "@avana/config";
import { createDbClient } from "./client.js";
import { up as up0001 } from "./migrations/0001_init.js";
import { up as up0002 } from "./migrations/0002_auth.js";
import { up as up0003 } from "./migrations/0003_learning_core.js";
import { up as up0004 } from "./migrations/0004_lesson_publication.js";
import { up as up0005 } from "./migrations/0005_ai_learning_engine.js";
import { up as up0006 } from "./migrations/0006_generation_idempotency.js";
import { up as up0007 } from "./migrations/0007_generation_jobs.js";
import { up as up0008 } from "./migrations/0008_content_review.js";
import { up as up0009 } from "./migrations/0009_study_consumption.js";
import { up as up0010 } from "./migrations/0010_user_flashcard_schedules.js";
import { up as up0011 } from "./migrations/0011_exams_configuration.js";
import { up as up0012 } from "./migrations/0012_taxonomy_lesson_relations.js";
import { up as up0013 } from "./migrations/0013_document_module_invariant.js";
import { up as up0014 } from "./migrations/0014_email_verification.js";
import { up as up0015 } from "./migrations/0015_study_conversations.js";
import { up as up0016 } from "./migrations/0016_study_sessions.js";
import { up as up0017 } from "./migrations/0017_flashcard_study_sessions.js";
import { up as up0018 } from "./migrations/0018_flashcard_session_reaction_ms.js";
import { up as up0019 } from "./migrations/0019_user_global_role.js";
import { up as up0020 } from "./migrations/0020_document_quality.js";
import { up as up0021 } from "./migrations/0021_content_packs.js";
import { up as up0022 } from "./migrations/0022_decouple_document_content.js";
import { up as up0023 } from "./migrations/0023_monetization_and_entitlements.js";
import { up as up0024 } from "./migrations/0024_official_courses_and_products.js";
import { up as up0025 } from "./migrations/0025_content_pack_review_workflow.js";
import { up as up0026 } from "./migrations/0026_migrate_legacy_content_packs_to_pending_review.js";
import { up as up0027 } from "./migrations/0027_blog_system.js";
import { up as up0028 } from "./migrations/0028_card_to_card_payments.js";
import { up as up0029 } from "./migrations/0029_device_and_single_session_security.js";
import { up as up0030 } from "./migrations/0030_content_export_import.js";
import { up as up0031 } from "./migrations/0031_widen_generation_keys.js";
import { up as up0032 } from "./migrations/0032_resumable_generation_chunks.js";
import { up as up0033 } from "./migrations/0033_widen_quiz_attempts_topic.js";
import { up as up0034 } from "./migrations/0034_generation_lease_infrastructure.js";
import { up as up0035 } from "./migrations/0035_content_pricing_and_entitlements.js";
import { up as up0036 } from "./migrations/0036_backfill_content_products.js";
import { up as up0037 } from "./migrations/0037_backfill_canonical_content_pricing.js";
import { up as up0038 } from "./migrations/0038_document_generation_progress.js";
import { up as up0039 } from "./migrations/0039_phone_verification.js";
import { up as up0040 } from "./migrations/0040_quiz_attempts_snapshot_and_metrics.js";
import { up as up0041 } from "./migrations/0041_module_preview_lesson_id.js";
import { up as up0042 } from "./migrations/0042_special_exam_entitlements.js";
import { up as up0043 } from "./migrations/0043_notifications.js";
import { up as up0044 } from "./migrations/0044_lesson_annotations_and_reports.js";

function localConnectionString(): string {
  const user = "avana";
  const password = "avana";
  const host = "127.0.0.1";
  const port = "5432";
  const db = "avana";
  return `postgres://${user}:${password}@${host}:${port}/${db}`;
}

loadMonorepoEnv();
const connectionString = process.env.DATABASE_URL ?? localConnectionString();

async function runMigrations() {
  console.log("Running AVANA database migrations...");
  const { db, close } = createDbClient(connectionString);

  try {
    console.log("Applying 0001_init...");
    await up0001(db);
    console.log("Applying 0002_auth...");
    await up0002(db);
    console.log("Applying 0003_learning_core...");
    await up0003(db);
    console.log("Applying 0004_lesson_publication...");
    await up0004(db);
    console.log("Applying 0005_ai_learning_engine...");
    await up0005(db);
    console.log("Applying 0006_generation_idempotency...");
    await up0006(db);
    console.log("Applying 0007_generation_jobs...");
    await up0007(db);
    console.log("Applying 0008_content_review...");
    await up0008(db);
    console.log("Applying 0009_study_consumption...");
    await up0009(db);
    console.log("Applying 0010_user_flashcard_schedules...");
    await up0010(db);
    console.log("Applying 0011_exams_configuration...");
    await up0011(db);
    console.log("Applying 0012_taxonomy_lesson_relations...");
    await up0012(db);
    console.log("Applying 0013_document_module_invariant...");
    await up0013(db);
    console.log("Applying 0014_email_verification...");
    await up0014(db);
    console.log("Applying 0015_study_conversations...");
    await up0015(db);
    console.log("Applying 0016_study_sessions...");
    await up0016(db);
    console.log("Applying 0017_flashcard_study_sessions...");
    await up0017(db);
    console.log("Applying 0018_flashcard_session_reaction_ms...");
    await up0018(db);
    console.log("Applying 0019_user_global_role...");
    await up0019(db);
    console.log("Applying 0020_document_quality...");
    await up0020(db);
    console.log("Applying 0021_content_packs...");
    await up0021(db);
    console.log("Applying 0022_decouple_document_content...");
    await up0022(db);
    console.log("Applying 0023_monetization_and_entitlements...");
    await up0023(db);
    console.log("Applying 0024_official_courses_and_products...");
    await up0024(db);
    console.log("Applying 0025_content_pack_review_workflow...");
    await up0025(db);
    console.log("Applying 0026_migrate_legacy_content_packs_to_pending_review...");
    await up0026(db);
    console.log("Applying 0027_blog_system...");
    await up0027(db);
    console.log("Applying 0028_card_to_card_payments...");
    await up0028(db);
    console.log("Applying 0029_device_and_single_session_security...");
    await up0029(db);
    console.log("Applying 0030_content_export_import...");
    await up0030(db);
    console.log("Applying 0031_widen_generation_keys...");
    await up0031(db);
    console.log("Applying 0032_resumable_generation_chunks...");
    await up0032(db);
    console.log("Applying 0033_widen_quiz_attempts_topic...");
    await up0033(db);
    console.log("Applying 0034_generation_lease_infrastructure...");
    await up0034(db);
    console.log("Applying 0035_content_pricing_and_entitlements...");
    await up0035(db);
    console.log("Applying 0036_backfill_content_products...");
    await up0036(db);
    console.log("Applying 0037_backfill_canonical_content_pricing...");
    await up0037(db);
    console.log("Applying 0038_document_generation_progress...");
    await up0038(db);
    console.log("Applying 0039_phone_verification...");
    await up0039(db);
    console.log("Applying 0040_quiz_attempts_snapshot_and_metrics...");
    await up0040(db);
    console.log("Applying 0041_module_preview_lesson_id...");
    await up0041(db);
    console.log("Applying 0042_special_exam_entitlements...");
    await up0042(db);
    console.log("Applying 0043_notifications...");
    await up0043(db);
    console.log("Applying 0044_lesson_annotations_and_reports...");
    await up0044(db);

    console.log("All database migrations applied successfully.");
  } catch (error) {
    console.error("Migration failed:", error);
    process.exit(1);
  } finally {
    await close();
  }
}

await runMigrations();
