import pg from "pg";
import { randomUUID } from "node:crypto";
import { calculateSpecialExamPrice } from "@avana/domain";

async function main() {
  const pool = new pg.Pool({
    connectionString:
      process.env.DATABASE_URL ||
      "postgres://avana:avana@127.0.0.1:5432/avana?sslmode=disable",
  });

  console.log("=== RECONCILING SPECIAL EXAMS ACROSS DATABASE ===");

  const coursesRes = await pool.query(
    "SELECT id, organization_id, name FROM courses WHERE deleted_at IS NULL ORDER BY name",
  );

  console.log(`Found ${coursesRes.rows.length} active courses.`);

  let totalCourseExamsCreated = 0;
  let totalCourseExamsUpdated = 0;
  let totalCourseExamsActive = 0;

  let totalChapterExamsCreated = 0;
  let totalChapterExamsUpdated = 0;
  let totalChapterExamsActive = 0;

  for (const course of coursesRes.rows) {
    const courseId = course.id;
    const orgId = course.organization_id;
    const courseName = course.name;

    // 1. Evaluate Course candidate question count
    const courseQCountRes = await pool.query(
      `SELECT COUNT(DISTINCT q.id) as count
       FROM quiz_questions q
       JOIN quizzes pz ON q.quiz_id = pz.id
       WHERE (
         pz.course_id = $1
         OR q.lesson_id IN (
           SELECT l.id FROM lessons l
           JOIN modules m ON l.module_id = m.id
           WHERE m.course_id = $1 AND l.deleted_at IS NULL AND m.deleted_at IS NULL
         )
       )`,
      [courseId],
    );
    const courseQCount = parseInt(courseQCountRes.rows[0]?.count || "0", 10);
    const isCourseSufficient = courseQCount >= 80;
    const courseCode = `special-exam-course-${courseId}-80`;
    const coursePrice = calculateSpecialExamPrice(80); // 40,000

    const existingCourseProd = await pool.query(
      "SELECT id, metadata FROM products WHERE code = $1",
      [courseCode],
    );

    const now = new Date().toISOString();
    const courseMeta = {
      questionCount: 80,
      difficulty: "medium",
      scope: { courseId, topics: [courseName] },
      blueprint: [{ name: courseName, courseId, count: 80 }],
      publicationStatus: isCourseSufficient ? "published" : "draft",
      poolStatus: isCourseSufficient ? "sufficient" : "insufficient",
      targetType: "course",
      targetId: courseId,
      availableQuestions: courseQCount,
      autoGenerated: true,
      lastReconciledAt: now,
    };

    if (existingCourseProd.rows.length > 0) {
      await pool.query(
        `UPDATE products
         SET title = $1, description = $2, price = $3, active = $4, metadata = $5, updated_at = NOW()
         WHERE code = $6`,
        [
          `آزمون جامع: ${courseName}`,
          `آزمون جامع شبیه‌ساز ۸۰ سؤالی از کلیه مباحث دوره ${courseName}`,
          coursePrice,
          isCourseSufficient,
          JSON.stringify(courseMeta),
          courseCode,
        ],
      );
      totalCourseExamsUpdated++;
    } else {
      await pool.query(
        `INSERT INTO products (id, code, type, title, description, price, currency, target_type, target_id, active, metadata, created_at, updated_at)
         VALUES ($1, $2, 'special_exam', $3, $4, $5, 'toman', 'special_exam', NULL, $6, $7, NOW(), NOW())`,
        [
          randomUUID(),
          courseCode,
          `آزمون جامع: ${courseName}`,
          `آزمون جامع شبیه‌ساز ۸۰ سؤالی از کلیه مباحث دوره ${courseName}`,
          coursePrice,
          isCourseSufficient,
          JSON.stringify(courseMeta),
        ],
      );
      totalCourseExamsCreated++;
    }

    if (isCourseSufficient) totalCourseExamsActive++;
    console.log(
      `  Course "${courseName}": ${courseQCount} questions -> ${isCourseSufficient ? "ACTIVE (80q, 40,000 T)" : "INACTIVE (< 80q)"}`,
    );

    // 2. Reconcile all modules in this course
    const modulesRes = await pool.query(
      "SELECT id, title, document_id FROM modules WHERE course_id = $1 AND deleted_at IS NULL ORDER BY sort_order",
      [courseId],
    );

    for (const mod of modulesRes.rows) {
      const moduleId = mod.id;
      const modTitle = mod.title;
      const docId = mod.document_id;

      // Evaluate Chapter candidate question count
      const chapterQCountRes = await pool.query(
        `SELECT COUNT(DISTINCT q.id) as count
         FROM quiz_questions q
         JOIN quizzes pz ON q.quiz_id = pz.id
         WHERE (
           q.lesson_id IN (
             SELECT l.id FROM lessons l
             WHERE l.module_id = $1 AND l.deleted_at IS NULL
           )
           OR ($2::uuid IS NOT NULL AND pz.document_id = $2::uuid)
         )`,
        [moduleId, docId],
      );
      const chapterQCount = parseInt(chapterQCountRes.rows[0]?.count || "0", 10);
      const isChapterSufficient = chapterQCount >= 25;
      const chapterCode = `special-exam-chapter-${moduleId}-25`;
      const chapterPrice = calculateSpecialExamPrice(25); // 12,500

      const existingChapterProd = await pool.query(
        "SELECT id, metadata FROM products WHERE code = $1",
        [chapterCode],
      );

      const chapterMeta = {
        questionCount: 25,
        difficulty: "medium",
        scope: { courseId, moduleId, topics: [modTitle] },
        blueprint: [{ name: modTitle, courseId, moduleId, count: 25 }],
        publicationStatus: isChapterSufficient ? "published" : "draft",
        poolStatus: isChapterSufficient ? "sufficient" : "insufficient",
        targetType: "module",
        targetId: moduleId,
        availableQuestions: chapterQCount,
        autoGenerated: true,
        lastReconciledAt: now,
      };

      if (existingChapterProd.rows.length > 0) {
        await pool.query(
          `UPDATE products
           SET title = $1, description = $2, price = $3, active = $4, metadata = $5, updated_at = NOW()
           WHERE code = $6`,
          [
            `آزمون فصل: ${modTitle}`,
            `آزمون شبیه‌ساز و تخصصی ۲۵ سؤالی از مباحث فصل ${modTitle}`,
            chapterPrice,
            isChapterSufficient,
            JSON.stringify(chapterMeta),
            chapterCode,
          ],
        );
        totalChapterExamsUpdated++;
      } else {
        await pool.query(
          `INSERT INTO products (id, code, type, title, description, price, currency, target_type, target_id, active, metadata, created_at, updated_at)
           VALUES ($1, $2, 'special_exam', $3, $4, $5, 'toman', 'special_exam', NULL, $6, $7, NOW(), NOW())`,
          [
            randomUUID(),
            chapterCode,
            `آزمون فصل: ${modTitle}`,
            `آزمون شبیه‌ساز و تخصصی ۲۵ سؤالی از مباحث فصل ${modTitle}`,
            chapterPrice,
            isChapterSufficient,
            JSON.stringify(chapterMeta),
          ],
        );
        totalChapterExamsCreated++;
      }

      if (isChapterSufficient) totalChapterExamsActive++;
      if (chapterQCount > 0) {
        console.log(
          `    Module "${modTitle}": ${chapterQCount} questions -> ${isChapterSufficient ? "ACTIVE (25q, 12,500 T)" : "INACTIVE (< 25q)"}`,
        );
      }
    }
  }

  console.log("\n=== RECONCILIATION SUMMARY ===");
  console.log(
    `Course Exams:  ${totalCourseExamsActive} active, ${totalCourseExamsCreated} created, ${totalCourseExamsUpdated} updated.`,
  );
  console.log(
    `Chapter Exams: ${totalChapterExamsActive} active, ${totalChapterExamsCreated} created, ${totalChapterExamsUpdated} updated.`,
  );

  await pool.end();
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
